language: cpp
compiler:
- gcc
- clang
env:
  matrix:
  - LIBCXX=true BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="master"
  - LIBCXX=true BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="master"
  - LIBCXX=false BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="master"
  - LIBCXX=false BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="master"
  - LIBCXX=true BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="master"
  - LIBCXX=true BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="master"
  - LIBCXX=false BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="master"
  - LIBCXX=false BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="master"

  - LIBCXX=true BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.57.0"
  - LIBCXX=true BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.57.0"
  - LIBCXX=false BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.57.0"
  - LIBCXX=false BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.57.0"
  - LIBCXX=true BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.57.0"
  - LIBCXX=true BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.57.0"
  - LIBCXX=false BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.57.0"
  - LIBCXX=false BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.57.0"

  - LIBCXX=true BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.56.0"
  - LIBCXX=true BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.56.0"
  - LIBCXX=false BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.56.0"
  - LIBCXX=false BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.56.0"
  - LIBCXX=true BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.56.0"
  - LIBCXX=true BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.56.0"
  - LIBCXX=false BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.56.0"
  - LIBCXX=false BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.56.0"

  - LIBCXX=true BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.55.0"
  - LIBCXX=true BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.55.0"
  - LIBCXX=false BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.55.0"
  - LIBCXX=false BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.55.0"
  - LIBCXX=true BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.55.0"
  - LIBCXX=true BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.55.0"
  - LIBCXX=false BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.55.0"
  - LIBCXX=false BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.55.0"
  global:
  - GCC_VERSION="4.9"
  - BII_BOOST_VERBOSE="ON"
  - secure: "rVmIQvzgsDqQTNG4e5XqgzOjeQrGlyz8lwTOzO+1xpaJA8oTfnLutkRLSNiTiCIGV5EmHFNTd7RI99AeLMgDSWc16cKfEfJxkkNmdp8YSjfhfchrDoD8xVVSxJ0xLpAkHzpdi+3AAQlqqM4ywobKeyxitiGSq7J8/KdkbzRRan0="

matrix:
  exclude:
  - compiler: gcc
    env: LIBCXX=true BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="master"
  - compiler: gcc
    env: LIBCXX=true BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="master"
  - compiler: gcc
    env: LIBCXX=true BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="master"
  - compiler: gcc
    env: LIBCXX=true BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="master"

  - compiler: gcc
    env: LIBCXX=true BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.57.0"
  - compiler: gcc
    env: LIBCXX=true BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.57.0"
  - compiler: gcc
    env: LIBCXX=true BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.57.0"
  - compiler: gcc
    env: LIBCXX=true BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.57.0"

  - compiler: gcc
    env: LIBCXX=true BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.56.0"
  - compiler: gcc
    env: LIBCXX=true BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.56.0"
  - compiler: gcc
    env: LIBCXX=true BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.56.0"
  - compiler: gcc
    env: LIBCXX=true BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.56.0"

  - compiler: gcc
    env: LIBCXX=true BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.55.0"
  - compiler: gcc
    env: LIBCXX=true BUILD_TYPE=Debug BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.55.0"
  - compiler: gcc
    env: LIBCXX=true BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON" BII_BOOST_TRACK="1.55.0"
  - compiler: gcc
    env: LIBCXX=true BUILD_TYPE=Release BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF" BII_BOOST_TRACK="1.55.0"

before_install:
- if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
- if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
- sudo apt-get update -qq

- if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-${GCC_VERSION}; fi
- if [ "$CXX" == "g++" ]; then sudo apt-get install -qq gcc-${GCC_VERSION}; fi
- if [ "$CXX" == "g++" ]; then sudo ln -s -v -f $(which g++-${GCC_VERSION}) /usr/bin/g++; fi
- if [ "$CXX" == "g++" ]; then sudo ln -s -v -f $(which gcc-${GCC_VERSION}) /usr/bin/gcc; fi

- if [ "$LIBCXX" == "true" ]; then cwd=$(pwd); fi
- if [ "$LIBCXX" == "true" ]; then export CXXFLAGS="-std=c++0x -stdlib=libc++"; fi
- if [ "$LIBCXX" == "true" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx; fi
- if [ "$LIBCXX" == "true" ]; then cd libcxx/lib && bash buildit; fi
- if [ "$LIBCXX" == "true" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
- if [ "$LIBCXX" == "true" ]; then sudo mkdir /usr/include/c++/v1; fi
- if [ "$LIBCXX" == "true" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
- if [ "$LIBCXX" == "true" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
- if [ "$LIBCXX" == "true" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi
- if [ "$LIBCXX" == "true" ]; then CXX_FLAGS="${CXX_FLAGS} -stdlib=libc++ -I/usr/include/c++/v1/"; fi
- if [ "$LIBCXX" == "true" ]; then CXX_LINKER_FLAGS="${CXX_LINKER_FLAGS} -stdlib=libc++ -L/usr/lib/ -lc++"; fi
- if [ "$LIBCXX" == "true" ]; then BII_BOOST_LIBCXX="ON"; else BII_BOOST_LIBCXX="OFF"; fi
- if [ "$CXX" == "clang++" ]; then export NO_CXX11_ALLOC="-DBOOST_NO_CXX11_ALLOCATOR=1"; fi

install:
- wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
- bii setup:cpp
- $CXX --version
- configure_params="-DCMAKE_CXX_COMPILER=$(which $CXX) -DBII_BOOST_VERBOSE=${BII_BOOST_VERBOSE} -DBII_BOOST_GLOBAL_USE_STATIC_LIBS=${BII_BOOST_GLOBAL_USE_STATIC_LIBS} -DBII_BOOST_LIBCXX=${BII_BOOST_LIBCXX} -DCMAKE_CXX_FLAGS=\"${NO_CXX11_ALLOC} ${CXX_FLAGS}\" -DCMAKE_EXE_LINKER_FLAGS=\"${CXX_LINKER_FLAGS}\""

script:
- bii init
- python generate.py "${passwords}" $BII_BOOST_TRACK
- bii find --update
- bii cpp:configure $configure_params || bii cpp:configure $configure_params
- bii cpp:build
